### ISSUE TITLE
Pusher Chatkit Is Now Gone

### ISSUE THREAD

**Issue by dcsena** [GetStream/pusher-chatkit-migration#4]
When I login to Pusher, chatkit doesn't even appear anymore in the dashboard. Step 1 is an export option but we can no longer export based on current instructions. Obviously this is not your fault, but any tips would be helpful.

**Comment by dcsena** [comment]
Update, export is now required via email. Read:
https://support.pusher.com/hc/en-us/articles/360007009257-Information-on-Chatkit-customer-migration

**Comment by tschellenbach** [comment]
First few exports and imports completed. It seems to work well so far.

**Comment by dcsena** [comment]
Thierry, recommend changing the README here. 
"Download your Chatkit export from the Pusher Dashboard."
This is no longer correct. You need to reach out to Pusher for them to do it for you.
